# Generated by Django 5.0.3 on 2024-04-27 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ManufacturerProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=0, max_digits=7)),
                ('old_price', models.DecimalField(blank=True, decimal_places=0, max_digits=7, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('additional_info', models.TextField(blank=True)),
                ('meta_tag', models.CharField(blank=True, max_length=100)),
                ('meta_description', models.CharField(blank=True, max_length=200)),
                ('meta_keywords', models.CharField(blank=True, max_length=200)),
                ('supplier_price', models.DecimalField(blank=True, decimal_places=0, max_digits=7, null=True)),
                ('competitor_price', models.DecimalField(blank=True, decimal_places=0, max_digits=7, null=True)),
                ('supplier_link', models.URLField(blank=True)),
                ('competitor_link', models.URLField(blank=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('photo', models.ImageField(blank=True, upload_to='products/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='electrazapi.categoryproduct')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='electrazapi.manufacturerproduct')),
            ],
        ),
    ]
