# Generated by Django 5.0.3 on 2024-05-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrazapi', '0002_alter_categoryproduct_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryproduct',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
