# Generated by Django 5.0.3 on 2024-05-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrazapi', '0003_alter_categoryproduct_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturerproduct',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
