# Generated by Django 5.0.3 on 2024-05-02 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrazapi', '0004_alter_manufacturerproduct_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='manufacturerproduct',
            name='country',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='electrazapi.country'),
            preserve_default=False,
        ),
    ]
