# Generated by Django 5.0.3 on 2024-05-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrazapi', '0005_country_manufacturerproduct_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('website', models.URLField()),
            ],
        ),
    ]
