# Generated by Django 5.0.3 on 2024-05-04 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrazapi', '0007_alter_supplier_name_alter_supplier_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='competitor_link',
        ),
        migrations.RemoveField(
            model_name='product',
            name='competitor_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='supplier_link',
        ),
        migrations.RemoveField(
            model_name='product',
            name='supplier_price',
        ),
        migrations.AddField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=7, null=True),
        ),
        migrations.CreateModel(
            name='ProductSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=0, max_digits=7)),
                ('link', models.URLField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electrazapi.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electrazapi.supplier')),
            ],
            options={
                'unique_together': {('product', 'supplier')},
            },
        ),
    ]
