# Generated by Django 5.0.3 on 2024-05-04 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electrazapi', '0008_remove_product_competitor_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='website',
            new_name='link',
        ),
    ]
