# Generated by Django 5.0.3 on 2024-05-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrazapi', '0009_rename_website_supplier_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='link',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
