# Generated by Django 5.0.3 on 2024-05-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrazapi', '0011_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsupplier',
            name='link',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='link',
            field=models.URLField(blank=True, default=''),
        ),
    ]
