# Generated by Django 5.0.3 on 2024-05-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrazapi', '0012_alter_productsupplier_link_alter_supplier_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsupplier',
            name='link',
            field=models.EmailField(max_length=200),
        ),
    ]
