# Generated by Django 5.0.3 on 2024-05-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrazapi', '0013_alter_productsupplier_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsupplier',
            name='link',
            field=models.URLField(),
        ),
    ]
