# Generated by Django 5.0.3 on 2024-05-16 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrazapi', '0022_alter_client_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='testmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boolean_field_nullable', models.BooleanField(blank=True, null=True)),
                ('char_field', models.CharField(max_length=10)),
                ('text_field', models.TextField()),
                ('integer_field', models.IntegerField(default=0)),
                ('small_integer_field', models.SmallIntegerField(default=0)),
                ('big_integer_field', models.BigIntegerField(default=0)),
                ('decimal_field', models.DecimalField(decimal_places=2, max_digits=10)),
                ('float_field', models.FloatField(default=0.0)),
                ('date_field', models.DateField()),
                ('datetime_field', models.DateTimeField()),
                ('time_field', models.TimeField()),
                ('file_field', models.FileField(upload_to='example/')),
                ('image_field', models.ImageField(upload_to='example/')),
                ('email_field', models.EmailField(max_length=254)),
                ('url_field', models.URLField()),
                ('slug_field', models.SlugField()),
                ('ip_address_field', models.GenericIPAddressField()),
            ],
            options={
                'verbose_name': 'testmodel',
                'verbose_name_plural': 'testmodel',
            },
        ),
        migrations.AlterModelOptions(
            name='manufacturerproduct',
            options={'verbose_name': 'производитель', 'verbose_name_plural': 'производители'},
        ),
        migrations.AlterField(
            model_name='manufacturerproduct',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electrazapi.country', verbose_name='страна'),
        ),
        migrations.AlterField(
            model_name='manufacturerproduct',
            name='name',
            field=models.CharField(max_length=100, verbose_name='производитель'),
        ),
    ]
