# Generated by Django 5.0.3 on 2024-05-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrazapi', '0023_testmodel_alter_manufacturerproduct_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testmodel',
            name='big_integer_field',
        ),
        migrations.RemoveField(
            model_name='testmodel',
            name='datetime_field',
        ),
        migrations.RemoveField(
            model_name='testmodel',
            name='decimal_field',
        ),
        migrations.RemoveField(
            model_name='testmodel',
            name='email_field',
        ),
        migrations.RemoveField(
            model_name='testmodel',
            name='ip_address_field',
        ),
        migrations.RemoveField(
            model_name='testmodel',
            name='small_integer_field',
        ),
        migrations.RemoveField(
            model_name='testmodel',
            name='time_field',
        ),
        migrations.RemoveField(
            model_name='testmodel',
            name='url_field',
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='char_field',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='date_field',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='file_field',
            field=models.FileField(blank=True, null=True, upload_to='example/'),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='float_field',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='image_field',
            field=models.ImageField(blank=True, null=True, upload_to='example/'),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='integer_field',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='slug_field',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='text_field',
            field=models.TextField(blank=True, null=True),
        ),
    ]
