# Generated by Django 5.0.3 on 2024-05-17 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electrazapi', '0024_remove_testmodel_big_integer_field_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='asdf',
        ),
        migrations.DeleteModel(
            name='testmodel',
        ),
    ]
