# Generated by Django 5.0.3 on 2024-05-17 11:44

import django.db.models.deletion
import locations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='страна')),
            ],
            options={
                'verbose_name': 'страна',
                'verbose_name_plural': 'страны',
            },
        ),
        migrations.CreateModel(
            name='LineMetro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='линия метро')),
            ],
            options={
                'verbose_name': 'линия метро',
                'verbose_name_plural': 'линии метро',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='город')),
                ('country', models.ForeignKey(default=locations.models.get_default_country, on_delete=django.db.models.deletion.PROTECT, to='locations.country', verbose_name='страна')),
            ],
            options={
                'verbose_name': 'город',
                'verbose_name_plural': 'города',
            },
        ),
        migrations.CreateModel(
            name='Metro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='станция метро')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.linemetro', verbose_name='линия метро')),
            ],
            options={
                'verbose_name': 'станция метро',
                'verbose_name_plural': 'станции метро',
            },
        ),
    ]
