# Generated by Django 5.0.3 on 2024-05-17 11:44

import django.db.models.deletion
import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='категория')),
                ('parent', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='products.productcategory')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='поставщик')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='номер телефона')),
                ('link', models.URLField(blank=True, default='', verbose_name='сайт')),
                ('discount', models.PositiveIntegerField(default=0, verbose_name='скидка %')),
                ('address', models.CharField(blank=True, max_length=20, verbose_name='адрес')),
                ('additionall', models.TextField(blank=True, default='', verbose_name='дополнительно')),
                ('city', models.ForeignKey(default=products.models.get_default_city, on_delete=django.db.models.deletion.PROTECT, to='locations.city', verbose_name='город')),
            ],
            options={
                'verbose_name': 'поставщик',
                'verbose_name_plural': 'поставщики',
            },
        ),
    ]
