# Generated by Django 5.0.3 on 2024-05-17 12:23

import django.db.models.deletion
import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='parent',
            field=models.ForeignKey(default=products.models.get_default_category, on_delete=django.db.models.deletion.CASCADE, to='products.productcategory', verbose_name='Родительская категория'),
        ),
        migrations.CreateModel(
            name='ProductManufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='производитель')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.country', verbose_name='страна')),
            ],
            options={
                'verbose_name': 'производитель',
                'verbose_name_plural': 'производители',
            },
        ),
        migrations.CreateModel(
            name='ProductSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='поставщик')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='номер телефона')),
                ('url', models.URLField(blank=True, default='', verbose_name='сайт')),
                ('discount', models.PositiveIntegerField(default=0, verbose_name='скидка %')),
                ('address', models.CharField(blank=True, max_length=20, verbose_name='адрес')),
                ('additionall', models.TextField(blank=True, default='', verbose_name='дополнительно')),
                ('city', models.ForeignKey(default=products.models.get_default_city, on_delete=django.db.models.deletion.PROTECT, to='locations.city', verbose_name='город')),
            ],
            options={
                'verbose_name': 'поставщик',
                'verbose_name_plural': 'поставщики',
            },
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
