# Generated by Django 5.0.3 on 2024-05-17 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productcategory_parent_productmanufacturer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='товар')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='цена')),
                ('old_price', models.PositiveIntegerField(default=0, verbose_name='старая цена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления')),
                ('price_updated_at', models.DateTimeField(default='', verbose_name='дата изменения цены')),
                ('additional_info', models.TextField(blank=True, verbose_name='дополнительно')),
                ('meta_tag', models.CharField(blank=True, max_length=100, verbose_name='тег')),
                ('meta_description', models.CharField(blank=True, max_length=200, verbose_name='описание')),
                ('meta_keywords', models.CharField(blank=True, max_length=200, verbose_name='ключевые слова')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='идентификатор url')),
                ('availability', models.PositiveIntegerField(default=0, verbose_name='в наличии')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.productcategory', verbose_name='категория')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.productmanufacturer', verbose_name='производитель')),
            ],
        ),
    ]
